apiVersion: v1
kind: Secret
metadata:
  name: mysqlpwd
data:
  rootHost: JQ==
  rootPassword: b2N0b2JlcmZlc3Q=
  rootUser: cm9vdA==

---

apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: todo-mysql
spec:
  secretName: mysqlpwd
  instances: 3
  router:
    instances: 1
  tlsUseSelfSigned: true