apiVersion: v1
kind: Service
metadata:
  labels:
    app: randomreads-web
    env: dev
    tier: frontend
  name: randomreads-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: randomreads-web
  type: LoadBalancer