apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/todo-volume/
